from fastapi import APIRouter, Depends, HTTPException, Form, status
from sqlalchemy.ext.asyncio import AsyncSession

from src.core.database import get_db
from src.core.security import verify_session  # 🔐 High-performance Redis session validation gate
from . import service

router = APIRouter(prefix="/payments", tags=["Secure Transaction Processing Architecture"])


@router.post("/order", status_code=status.HTTP_201_CREATED)
async def initialize_checkout_order(
    plan_name: str = Form(
        ..., 
        description="Target subscription plan selection string token: 'Premium_Monthly' or 'Elite_Semester'"
    ),
    user_id: str = Depends(verify_session),  # 🎯 Injects validated user ID straight from high-speed Redis caches
    db: AsyncSession = Depends(get_db)
):
    """
    Initializes a Razorpay checkout transaction loop. 
    Registers a PENDING transaction layout map within the system ledger.
    """
    return await service.create_payment_order(
        db=db, 
        user_id=user_id, 
        plan_name=plan_name
    )


@router.post("/verify", status_code=status.HTTP_200_OK)
async def verify_checkout_payment(
    razorpay_order_id: str = Form(..., description="The unique identity reference string generated by Razorpay client order handshakes"),
    razorpay_payment_id: str = Form(..., description="The tracking reference signature generated on successful consumer swipe interaction"),
    razorpay_signature: str = Form(..., description="Cryptographic authenticity signature token passed by the payment gateway provider"),
    user_id: str = Depends(verify_session),  # 🛡️ Guarantees that only authorized active profiles can submit verification loops
    db: AsyncSession = Depends(get_db)
):
    """
    Performs critical SHA256 HMAC cryptographic check verification lookups on transaction parameters.
    Upon successful validation, updates status records to SUCCESS and activates plan premium privileges.
    """
    if not all([razorpay_order_id, razorpay_payment_id, razorpay_signature]):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, 
            detail="Missing required Razorpay validation transaction signature block parameters."
        )
        
    return await service.verify_payment_authenticity(
        db=db,
        user_id=user_id,
        razorpay_order_id=razorpay_order_id,
        razorpay_payment_id=razorpay_payment_id,
        razorpay_signature=razorpay_signature
    )